// src/renderer/src/lib/components/ui/input.svelte
<script lang="ts">
	import type { HTMLInputAttributes } from 'svelte/elements';
	import { cn } from '~/lib/utils';

	type Props = {} & HTMLInputAttributes;

	const { class: className, ...rest }: Props = $props();
</script>

<input
	{...rest}
	class={cn(
		'border h-7 px-2 rounded border-neutral-200 w-full focus-within:outline-neutral-400 focus-within:outline-1 disabled:text-neutral-400',
		className
	)}
/>

// src/renderer/src/components/ui/input.tsx
import * as React from "react";

import { cn } from "~/lib/utils";

export interface InputProps
  extends React.InputHTMLAttributes<HTMLInputElement> {}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className, type, ...props }, ref) => {
    return (
      <input
        type={type}
        className={cn(
          "flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50",
          className,
        )}
        ref={ref}
        spellCheck={false}
        {...props}
      />
    );
  },
);
Input.displayName = "Input";

export { Input };
