// src/renderer/src/components/ui/slider.tsx
import * as SliderPrimitive from "@radix-ui/react-slider";
import * as React from "react";

import { cn } from "~/lib/utils";

const Slider = React.forwardRef<
  React.ElementRef<typeof SliderPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof SliderPrimitive.Root>
>(({ className, ...props }, ref) => (
  <SliderPrimitive.Root
    ref={ref}
    className={cn(
      "relative flex w-full touch-none select-none items-center",
      className,
    )}
    {...props}
  >
    <SliderPrimitive.Track className="relative h-1.5 w-full grow overflow-hidden rounded-full bg-primary/20">
      <SliderPrimitive.Range className="absolute h-full bg-primary" />
    </SliderPrimitive.Track>
    <SliderPrimitive.Thumb className="block h-4 w-4 rounded-full border border-primary/50 bg-background shadow transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50" />
  </SliderPrimitive.Root>
));
Slider.displayName = SliderPrimitive.Root.displayName;

export { Slider };

// src/renderer/src/lib/components/ui/slider.svelte
<script lang="ts">
	import { Slider } from '@ark-ui/svelte/slider';
	import type { SliderRootProps } from '@ark-ui/svelte/slider';

	const { ...props }: SliderRootProps = $props();
</script>

<Slider.Root {...props}>
	<Slider.ValueText />
	<Slider.Control class="flex items-center">
		<Slider.Track class="bg-neutral-200 dark:bg-neutral-100/10 h-1 rounded-full grow">
			<Slider.Range class="bg-neutral-800 dark:bg-neutral-200 h-1 rounded-full" />
		</Slider.Track>
		<Slider.Thumb
			class="size-4 flex items-center justify-center rounded-full bg-neutral-50 dark:bg-neutral-200 shadow border border-neutral-800"
			index={0}
		>
			<Slider.HiddenInput />
		</Slider.Thumb>
	</Slider.Control>
</Slider.Root>
