// src/renderer/src/App.tsx
import { AppMain } from "./components/app-main";
import { Layout, Aside, Main } from "./components/layout";
import { Sidebar } from "./components/sidebar";

function App() {
	return (
		<Layout>
			<Aside>
				<Sidebar />
			</Aside>
			<Main>
				<AppMain />
			</Main>
		</Layout>
	);
}

export default App;

// src/renderer/src/App.svelte
<script lang="ts">
	import { LayoutRoot, Sider, Content } from './lib/components/Layout';
	import { Sidebar } from './lib/components/Sidebar';
	import { AppMain } from './lib/components/AppMain';
</script>

<div class="aaa">
	<LayoutRoot>
		<Sider>
			<Sidebar />
		</Sider>
		<Content>
			<AppMain />
		</Content>
	</LayoutRoot>
</div>
