// pxloss.uimo.dev/src/routes/home/Hero.svelte
<script lang="ts">
	import Nav from './Nav.svelte';
</script>

<section
	class="max-w-7xl mx-auto px-5 md:px-10 lg:px-20 h-screen flex items-center justify-center gap-0 lg:gap-10 flex-col lg:flex-row min-h-[700px] relative"
>
	<Nav />

	<div class="w-full lg:w-2/5 text-center lg:text-left">
		<h1 class="text-3xl lg:text-5xl font-bold">像素丢失</h1>
		<h2 class="text-xl lg:text-3xl font-semibold mt-2 lg:mt-4">美观易用的开源图片压缩软件</h2>

		<a
			class="mt-10 rounded px-8 py-2 text-xl bg-blue-600 hover:bg-blue-700 active:bg-blue-800 text-white inline-flex"
			href="https://www.123pan.com/s/072SVv-Dl7cv"
			target="_blank"
			rel="noreferrer">免费下载</a
		>
		<p class="mt-2 text-sm text-zinc-700">支持 macOS 和 Windows 系统</p>
	</div>

	<img
		class="w-full drop-shadow-2xl lg:w-3/5 mt-10 lg:mt-0 rounded-lg"
		src="/images/intro.webp"
		alt=""
	/>
</section>

// site/components/Hero.tsx
import Image from "next/image";
import styles from "~/styles/Hero.module.css";

export default function Hero() {
  return (
    <div className={styles.hero}>
      <article>
        <h1 className={styles.h1}>像素丢失</h1>
        <h2 className={styles.h2}>面向现代 Web 应用的开源图片压缩软件</h2>
        <p>通过最新算法，在不损失视觉质量的前提下，大幅度减少图片文件大小</p>
        <p className={styles.download}>
          <a
            className={styles.github}
            href="https://github.com/9t5c/pixel-loss/releases"
            target="_blank"
            rel="noreferrer"
          >
            免费下载
          </a>
          <a
            className={styles.china}
            href="https://www.123pan.com/s/072SVv-Dl7cv"
            target="_blank"
            rel="noreferrer"
          >
            网盘下载
          </a>
        </p>
        <p className={styles.system}>支持 macOS 和 Windows 系统</p>
        <p className={styles.version}>版本：v1.2.0，更新日期：2023/02/01</p>
      </article>

      <figcaption className={styles.screenshot}>
        <Image
          src="/screenshot.webp"
          width={1760}
          height={1160}
          alt="screenshot"
        />
      </figcaption>
    </div>
  );
}
